apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-dou2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jirg-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-dou2@sha256:a5efa964797a8ac09e6594e4af07ec3150ab750c649af3af525ee53e7ef9a4fd
        name: my-nodejs
        resources: {}
status: {}
